# Generated by Django 5.2.8 on 2025-11-09 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stan_magazynowy', models.PositiveIntegerField(default=0)),
                ('dostepny', models.BooleanField(default=True)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produkty', to='sklep.kategoria')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
    ]
