# Generated by Django 5.2.7 on 2026-01-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'ordering': ['nazwa'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='produkt',
            options={'ordering': ['-utworzono'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterField(
            model_name='produkt',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='produkt',
            constraint=models.CheckConstraint(condition=models.Q(('cena__gte', 0)), name='cena_nieujemna'),
        ),
        migrations.AddConstraint(
            model_name='produkt',
            constraint=models.CheckConstraint(condition=models.Q(('stan_magazynowy__gte', 0)), name='stan_nieujemny'),
        ),
    ]
