# Generated by Django 5.2.7 on 2026-01-23 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_alter_kategoria_options_alter_produkt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('nowe', 'Nowe'), ('oplacone', 'Opłacone'), ('wyslane', 'Wysłane')], default='nowe', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PozycjaZamowienia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField(default=1)),
                ('cena_przy_zakupie', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklep.produkt')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pozycje', to='sklep.zamowienie')),
            ],
        ),
    ]
